create routing & project outline
alyonastartseva/blogging-platform pull request #10
Opened 2023-09-04 13:17 UTC by MuraPro

![1](https://github.com/alyonastartseva/blogging-platform/assets/78410784/a35430c0-31c3-4b80-a9e4-81ac21c110dc)
![2](https://github.com/alyonastartseva/blogging-platform/assets/78410784/9e34ccfd-cbc0-43f0-b4f9-5d2a82bb7863)

2023-09-08 12:11 UTC, EgorBrotsman commented on src/pages/ArticlePage/ArticleCard.tsx
> +export default ArticleCard;
Страница должна возвращать необходимый компанент а ты перетащил ArticleCard в page когда он должен находится в components тобишь у тебя в файле page должен быть фаил ArticlePage и внутри index.ts который буде выглядеть так 
`import {ArticleCard} from '../../components/ArticleCard'
 const ArticlePage =() => <ArticleCard/>
`
Остальные файлы по аналогии

2023-09-08 12:14 UTC, EgorBrotsman commented on src/pages/ArticlePage/ArticleCard.tsx
> +export default ArticleCard;
Комментарий выше про весь фаил не верновыделил просто)

2023-09-08 12:18 UTC, MuraPro commented on .prettierrc
> +  "semi": true
bracketSameLine / jsxBracketSameLine - автоматическое форматирование кода в удобочитаемый вид
Semi — true/ false - нужно ли добавлять точку с запятой в конце строк.
Tab Width — укажите, сколько пробелов должно вставляться при табуляции.можно удалить если мешает

2023-09-08 12:19 UTC, MuraPro commented on package.json
> -    "start": "react-scripts start",
я тут конфликты фиксил походу я его случайно удалил .

2023-09-08 12:19 UTC, y-shatulo commented
У тебя реализован функционал, который не описан в задаче. В описании твоей задачи указан только роутинг, поэтому давать какие-то комментарии по остальному я затрудняюсь. Предлагаю сделать PR, соответствующий требованиям тз по задаче

2023-09-08 12:20 UTC, MuraPro commented on src/components/App/App.tsx
> +      <Route path={`${ERoutes.BLOGS}/:id`} element={<BlogPage />} />
Мне нужно по заданию пока только со списка блогов к странице блога со списком статей, на сами статьи пока ненужно было делать

2023-09-08 12:21 UTC, MuraPro commented on package.json
> +    "node-sass": "^9.0.0",
ок

2023-09-08 12:23 UTC, EgorBrotsman commented on src/components/App/App.tsx
> +      <Route path={`${ERoutes.BLOGS}/:id`} element={<BlogPage />} />
Создание роутинга для перехода к статьям по выбранному блогу - это описание твоей карточки)

2023-09-08 12:33 UTC, MuraPro commented on src/components/App/App.tsx
> +      <Route path={`${ERoutes.BLOGS}/:id`} element={<BlogPage />} />
Расширить компонент-карточку блога с возможностью клика по ней и дальнейшему переходу к странице блога со всеми статьями (в рамках данной задачи страницу блога сделать пустышкой).

Переход к статьям поможет реализовать библиотека [React-Router](https://reactrouter.com/en/main/start/concepts).

При наведении на карточку менять курсор пользователя и добавлять тенюшку к карточке.

2023-09-08 17:34 UTC, Mauladen requested changes

2023-09-09 09:03 UTC, MuraPro commented on src/redux/services/commentsApi.ts
> +    getArticles: build.query({
ok

2023-09-09 09:03 UTC, MuraPro commented on src/redux/services/articlesApi.ts
> +      query: () => `articles`,
ok

2023-09-09 09:03 UTC, MuraPro commented on src/redux/services/commentsApi.ts
> +      query: () => `comments`,
ok

2023-09-09 09:04 UTC, MuraPro commented on src/redux/store.ts
> +  middleware: (getDefaultMiddleware) => [...getDefaultMiddleware(), blogsApi.middleware],
ok

2023-09-09 09:26 UTC, shaltus reviewed
Замечаний нет, проверено.

2023-09-09 11:02 UTC, MuraPro reviewed
Проверенно

2023-09-10 08:40 UTC, MuraPro reviewed
ok

2023-09-10 08:41 UTC, MuraPro reviewed
ok

2023-09-10 09:38 UTC, alyonastartseva requested changes

2023-09-10 09:38 UTC, alyonastartseva commented on src/routes/index.ts
> +enum ERoutes {
подход для описания роутинга хорош

Обычно для каждого роута помимо пути и компонента нужны доп.пропсы. Например, пропс exact.
Чтобы это не хардкодить и не писать ручками создают конфигурацию для роутов, например:

```
[{
    path: '/',
    exact: true,
    component: Home,
    name: 'root',
    isProtected: false
  }, ...],
```

А потом из этой конфигурации маппят роуты (в нашем случае это делается в компоненте App)

Когда в приложении будет появляться новая страница - достаточно описать конфиг для этого роута и всё будет работать "из-под коробки"

2023-09-10 09:38 UTC, alyonastartseva commented on src/components/Header/Header.module.scss
> +  //   border: 1px solid red;
лучше не оставлять закомментированный код - сразу удалять, чтоб не было лишнего мусора

2023-09-10 09:38 UTC, alyonastartseva commented on src/components/Header/Header.tsx
> +const PageHeader: React.FC = () => (
import React, { FC } from 'react

2023-09-10 09:38 UTC, alyonastartseva commented on src/components/Layout/Layout.module.scss
> +  //   border: 1px solid red;
удалить закомментированный код

2023-09-10 14:14 UTC, MuraPro commented on src/components/App/App.css
убрал

2023-09-10 14:18 UTC, MuraPro commented on src/routes/index.ts
> +enum ERoutes {
Алёна, то что ты написала, если я правильно понял это практика react-router-dom v5, я нашел вроде схему v6, не уверен что это именно то что нужно, тем не менее посмотри пожалуйста, прокомментируй данную практику. Все что нужно посмотреть комапанент App. Сейчас запушу.

2023-09-10 14:18 UTC, MuraPro commented on src/components/Header/Header.module.scss
> +  //   border: 1px solid red;
убрал

2023-09-10 14:18 UTC, MuraPro commented on src/components/Header/Header.tsx
> +const PageHeader: React.FC = () => (
ок

2023-09-10 14:19 UTC, MuraPro commented on src/components/Layout/Layout.module.scss
> +  //   border: 1px solid red;
убрал

2023-09-11 07:36 UTC, alyonastartseva requested changes

2023-09-11 07:36 UTC, alyonastartseva commented on src/components/Layout/Layout.tsx
> +const Layout: React.FC = (): JSX.Element => (
FC также сразу импортнуть

2023-09-11 07:36 UTC, alyonastartseva commented on src/routes/index.ts
> +enum ERoutes {
Именно! Только я хотела сначала, чтоб ручками это всё реализовали, без обёртки-хука useRoutes. В целом - ок, пусть будет. Здорово, что поресёрчил. В "молодых" проектах этот хук и юзают, с 5 версией делают, как описала выше (об этом полезно знать и понимать, как оно работает)

Оставила небольшие комменты в App-компоненте

2023-09-11 07:36 UTC, alyonastartseva commented on src/components/App/App.tsx
> +    {
массив лучше вынести в константу и в отдельный файл, чтобы компонент App излишне не перегружать при добавлении новых роутов

можно положить в /routes

2023-09-11 07:36 UTC, alyonastartseva commented on src/components/App/App.tsx
> +  return <>{routes}</>;
почему не просто `return routes`?

2023-09-11 10:20 UTC, MuraPro commented on src/routes/index.ts
> +enum ERoutes {
Просмотрел и поправил.

2023-09-11 10:20 UTC, MuraPro commented on src/components/Layout/Layout.tsx
> +const Layout: React.FC = (): JSX.Element => (
Поправил

2023-09-11 10:21 UTC, MuraPro commented on src/components/App/App.tsx
> +    {
Спасибо. Понял. Учту.

2023-09-11 10:21 UTC, MuraPro commented on src/components/App/App.tsx
> +    {
Поправил.

2023-09-11 10:24 UTC, MuraPro commented on src/components/App/App.tsx
> +  return <>{routes}</>;
На сколько я понял, роуты без фрагмента не выводятся.

2023-09-11 13:31 UTC, alyonastartseva requested changes

2023-09-11 13:31 UTC, alyonastartseva commented on src/components/App/App.tsx
> +  return <>{routes}</>;
не, не в этом дело
ты указал JSX.Element в return'е, а тип routes ReactElement - из-за этого ругается
без JSX.Element всё гуд работает

2023-09-11 13:43 UTC, alyonastartseva commented on src/routes/index.tsx
> +    { path: '/', element: <Navigate to={ERoutes.BLOGS} /> },
давай чтобы не мудрить с роутами сделаем так:
главная (домашняя страница) - список блогов
от неё уже переходим по конкретному блогу с id
+добавить для Not found обработку

2023-09-11 13:43 UTC, alyonastartseva commented on src/routes/index.tsx
> +  HOME = '/',
HOME ниже нигде не используется
но его и навряд ли нужно отдельно в енам зашивать

2023-09-11 13:54 UTC, alyonastartseva requested changes

2023-09-11 13:54 UTC, alyonastartseva commented on src/routes/index.tsx
> +    { path: '/', element: <Navigate to={ERoutes.BLOGS} /> },
т.е. в идеале не должно быть <Navigate to>
нужно выстроить структуру таким образом, чтобы в element'е всегда был реакт-компонент

2023-09-11 15:28 UTC, merged