BP857394-9_creating-article
alyonastartseva/blogging-platform pull request #13
Opened 2023-09-06 04:49 UTC by Mauladen

![](https://github.com/alyonastartseva/blogging-platform/assets/12824589/ab3b88d4-cf4f-4597-9e00-88dc572ee7f7)

2023-09-06 08:29 UTC, shaltus commented on src/components/CreateArticle/CreateArticle.tsx
> +        <Input style={{ width: '100%', height: '40px' }} placeholder="Введите заголовок статьи" />
обратила внимание, что у тебя многие стили дублируются прямо внутри компонентов Form.Item, Input и Button в return. Чтобы сделать код чище и более поддерживаемым, я бы порекомендовала вынести общие стили в отдельные константы вверху компонента

2023-09-06 08:29 UTC, shaltus commented on src/components/CreateArticle/CreateArticle.tsx
> +const CreateArticle: React.FC = () => {
можно импортировать в React, { useState, FC }

2023-09-06 08:42 UTC, EgorBrotsman commented on src/components/ModalGeneral/ModalGeneral.tsx
> +export default ModalGeneral;
Заем делать export default если можно сделать `export { ModalGeneral }` тем самым в index.ts мы избежим `export { default as ModalGeneral } from './ModalGeneral'` и сможем сделать более эстэтично чтоли `export { ModalGeneral } from './ModalGeneral'`

2023-09-06 08:55 UTC, EgorBrotsman commented on src/components/CreateArticle/CreateArticle.tsx
> +        style={{ marginBottom: '25px' }}
Можно импортировать стили компонента предать их в className={style.form-item} например, что позволит нам избавится от style и стилей в jsx

2023-09-06 08:56 UTC, EgorBrotsman commented on src/components/CreateArticle/CreateArticle.tsx
> +        <Button style={{ width: '320px', height: '40px' }} type="primary" htmlType="submit">
Из комментария выше следует что здесь можно поступить анолагично

2023-09-06 08:58 UTC, EgorBrotsman commented on src/components/CreateArticle/CreateArticle.tsx
> +        <Input style={{ width: '100%', height: '40px' }} placeholder="Введите заголовок статьи" />
Нам точно нужен width: 100% ? без него вроде тоже всё верно работает.

2023-09-06 09:16 UTC, Mauladen commented on src/components/CreateArticle/CreateArticle.tsx
> +        <Input style={{ width: '100%', height: '40px' }} placeholder="Введите заголовок статьи" />
Возможно и нет, чуть позже гляну

2023-09-06 09:49 UTC, EgorBrotsman commented on src/components/CreateArticle/CreateArticle.tsx
> +  const normFile = (event: any) => {
Нужно что-то решить с типизацией в ts event типизируется так event: React.FormEvent но возникает ошибка что у FormEvent нет fileList я пока сам не знаю как решить разбираюсь если есть идеи буду рад услышать)

2023-09-07 05:09 UTC, Mauladen commented on src/components/CreateArticle/CreateArticle.tsx
> +  const normFile = (event: any) => {
В данной ситуации я просто проигнорировал :)

2023-09-07 13:31 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +    <Form name="sign-in" layout="vertical" onFinish={(values) => console.log(values)}>
values затипизировать

2023-09-07 13:34 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +      <Form.Item style={{ marginBottom: '0px' }}>
лучше в стили вынести

2023-09-07 13:38 UTC, alyonastartseva commented on src/components/ModalGeneral/ModalGeneral.tsx
> +  const showModal = () => {
можно написать один обработчик аля changeVisibility, в которую передавать параметр видимости/невидимости

2023-09-07 13:40 UTC, alyonastartseva commented on src/components/ModalGeneral/ModalGeneral.type.ts
> +  children: React.ReactNode;
import { ReactNode } from 'react';

2023-09-07 17:03 UTC, Mauladen commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +    <Form name="sign-in" layout="vertical" onFinish={(values) => console.log(values)}>
Ну я делал Blog Platform, предыдущий проект, чтобы занового не делать структуру форм решил взять от туда :)

2023-09-08 06:15 UTC, Mauladen commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +    <Form name="sign-in" layout="vertical" onFinish={(values) => console.log(values)}>
Я это сделаю в следующей задачи

2023-09-09 04:00 UTC, alyonastartseva requested changes

2023-09-09 04:00 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +        const newValues = { ...values };
обработчик onFinish лучше вынести в функцию

Знаешь разницу при рендере между:
- onFinish={() => {}}
- onFinish={handleFinish} ?

2023-09-09 04:00 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +        console.log(newValues);
затесался console.log

2023-09-09 04:00 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +        console.log(newValues);
а если values.uploads === undefined?

2023-09-09 04:00 UTC, alyonastartseva commented on src/components/ModalGeneral/ModalGeneral.tsx
> +  const handleCancel = () => {
можно написать один обработчик changeVisibility, в которую передавать параметр видимости/невидимости, т.к. в текущей реализации функции служат для одного и того же

2023-09-09 05:52 UTC, Mauladen commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +        const newValues = { ...values };
Нет, этого я не знаю

2023-09-09 06:24 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +        const newValues = { ...values };
анонимная стрелочная функция () => {} создаётся каждый раз при рендере компонента (что влияет на производительность)
объявленная функция handleFinish кэшируется

2023-09-09 06:32 UTC, alyonastartseva requested changes

2023-09-09 06:32 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +const handleFinish = (values: TFormCreateArticle) => {
обработчик handleFinish лучше вынести в функцию в пределах компонента
т.к при привязке АПИ, вероятно, форма будет принимать пропс onCreate, который будет вызываться в этой функции

2023-09-09 06:35 UTC, Mauladen commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +const handleFinish = (values: TFormCreateArticle) => {
> обработчик handleFinish лучше вынести в функцию в пределах компонента т.к при привязке АПИ, вероятно, форма будет принимать пропс onCreate, который будет вызываться в этой функции

Исправил

2023-09-09 14:23 UTC, merged