Closes Bp857394-5
alyonastartseva/blogging-platform pull request #14
Opened 2023-09-06 12:49 UTC by EgorBrotsman

![2023-09-06_13-36-29](https://github.com/alyonastartseva/blogging-platform/assets/58328829/cd90b9bb-afbd-4f12-9beb-99e7abce8709)

2023-09-07 14:01 UTC, shaltus reviewed
замечаний нет ,проверено!

2023-09-08 11:21 UTC, MuraPro reviewed
Проверил, замечаний нет.

2023-09-09 16:14 UTC, alyonastartseva requested changes

2023-09-09 16:14 UTC, alyonastartseva commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +  <Form name="basic" layout="vertical" onFinish={(values) => console.log(values)}>
обработчик на onFinish лучше сразу вынести в отдельную функцию
ещё полезно будет посмотреть про разницу между onFinish={()=> {}} && onFinish={handleFinish}

2023-09-09 16:14 UTC, alyonastartseva commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      rules={[{ required: true, message: 'Please input blog name!' }]}
Label русский, а валидация на англ - давай упорядочим всё на рус (касается контролов и ниже)

2023-09-09 16:14 UTC, alyonastartseva commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      getValueFromEvent={(event: UploadProps) => event?.fileList}
давай переиспользуем готовый хелпер (после ребейза на dev)

2023-09-09 16:14 UTC, alyonastartseva commented on src/shared/components/ModalGeneral/ModalGeneral.tsx
> +    setIsModalOpen(false);
три функции, делающие одно и то же - бэд прэктис
можно написать один обработчик changeVisibility

P.S. после ребейза заиспользовать уже готовый аналогичный компонент

2023-09-09 16:14 UTC, alyonastartseva commented on src/shared/components/ModalGeneral/ModalGeneral.type.ts
> +	children: React.ReactNode,
import { ReactNode } from 'react';

2023-09-09 16:14 UTC, alyonastartseva commented on src/shared/components/ModalGeneral/index.ts
> +// eslint-disable-next-line import/prefer-default-export
опять дизейбл линтера? ;)

2023-09-09 16:14 UTC, alyonastartseva commented on src/shared/components/ModalGeneral/ModalGeneral.module.scss
пустой файлик?

2023-09-09 16:37 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreate.type.ts
> +  'Blog name': string;
решил что blog name лучше отражает к чему это имя относится)

2023-09-09 16:50 UTC, Mauladen requested changes

2023-09-09 16:53 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +import {FC} from 'react';
да нет вроде всё хорошо, прошолся format всё так и осталось

2023-09-09 17:03 UTC, Mauladen requested changes

2023-09-09 17:03 UTC, Mauladen commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog avatar"
`name` в данном случае должен быть backgroundImage

2023-09-09 17:03 UTC, Mauladen commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog name"
`name` в данном случае должен быть title

2023-09-09 17:03 UTC, Mauladen commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog author"
`name` в данном случае должен быть author

2023-09-10 05:24 UTC, alyonastartseva commented on src/components/FormCreateBlog/FormCreate.type.ts
> +  'Blog name': string;
тогда лучше через camelCase нотацию - blogName

и при использовании будет меньше "буков" и будет код быстрее писаться:
- blog.blogName || blog.name
- blog['Blog name']

Семантика в первом случае, вроде, не страдает

2023-09-10 10:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.module.scss
> +
исправил

2023-09-10 10:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreate.type.ts
> +  'Blog name': string;
исправил

2023-09-10 10:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +  <Form name="basic" layout="vertical" onFinish={(values) => console.log(values)}>
исправил

2023-09-10 10:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      rules={[{ required: true, message: 'Please input blog name!' }]}
исправил

2023-09-10 10:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      getValueFromEvent={(event: UploadProps) => event?.fileList}
исправил

2023-09-10 10:42 UTC, EgorBrotsman commented on src/shared/components/ModalGeneral/ModalGeneral.tsx
> +    setIsModalOpen(false);
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/shared/components/ModalGeneral/ModalGeneral.type.ts
> +	children: React.ReactNode,
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/shared/components/ModalGeneral/index.ts
> +// eslint-disable-next-line import/prefer-default-export
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/shared/components/ModalGeneral/ModalGeneral.module.scss
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +  <Form name="basic" layout="vertical" onFinish={(values) => console.log(values)}>
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +    <Form.Item<FormCreateBlogTypeInput>
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog avatar"
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog name"
исправил

2023-09-10 10:43 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +      name="Blog author"
исправил

2023-09-11 07:14 UTC, alyonastartseva requested changes

2023-09-11 07:14 UTC, alyonastartseva commented on src/components/App/App.tsx
> +const App: React.FC = () => <ModalGeneral titleModal='Создане нового блога' textButton='Создание блога'>
лучше пока что оставить предыдущий мок

2023-09-11 07:14 UTC, alyonastartseva commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +const handleFinish = (values: FormCreateBlogType) => {
обработчик handleFinish лучше вынести в функцию в пределах компонента
т.к при привязке АПИ, вероятно, форма будет принимать пропс onCreate, который будет вызываться в этой функции

2023-09-11 07:42 UTC, EgorBrotsman commented on src/components/App/App.tsx
> +const App: React.FC = () => <ModalGeneral titleModal='Создане нового блога' textButton='Создание блога'>
исправил

2023-09-11 07:42 UTC, EgorBrotsman commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +const handleFinish = (values: FormCreateBlogType) => {
исправил

2023-09-11 09:04 UTC, alyonastartseva approved these changes

2023-09-11 09:04 UTC, merged