Closes bp857394 17 article comments view
alyonastartseva/blogging-platform pull request #15
Opened 2023-09-08 13:32 UTC by shaltus

2023-09-08 13:36 UTC, shaltus commented
![image (2)](https://github.com/alyonastartseva/blogging-platform/assets/107109329/b690b55e-3af5-43bc-96c1-fd8037db74b3)

![image (3)](https://github.com/alyonastartseva/blogging-platform/assets/107109329/4336baec-e125-4de1-ba3f-aabc2a99b733)

2023-09-08 17:22 UTC, Mauladen commented on src/redux/commentsApi.ts
> +      query: () => `api/comments`
По данному эндпоинту ты получишь все комментарии которые существуют а не только конкретной статьи

2023-09-09 08:08 UTC, MuraPro commented on src/components/ArticleComments/ArticleComments.tsx
> +  const { data: comments = [] } = useGetCommentsQuery(articleId) as { data: TArrayComment };
Почему не проверяешь на наличие ошибок? Из этого хука можно вытянуть isError помимо данных. Мало ли прилетит ошибка, думаю стоит это учесть.

2023-09-09 08:09 UTC, MuraPro commented on src/components/ArticleComments/ArticleComments.tsx
> +  const renderComment = (comment: (typeof comments)[0]) => (
не совсем уверен что данная типизация верная, то есть ты проверяешь тип первого комментария и типизируешь по нему что ли???

2023-09-09 11:15 UTC, MuraPro reviewed
Проверил. Замечаний нет.

2023-09-09 16:39 UTC, Mauladen requested changes

2023-09-09 16:39 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +  );
Почему просто нельзя сделать так?

```typescript
if (isError) {
return <Alert message="Ошибка при загрузке комментариев" type="error" />
}
```

Если будет ошибка то оно отработает и не будет возвращён твой компонент, к тому же ты избавишься от лишнего кода который постоянно вызывает трудночитаемость

2023-09-09 16:39 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +        {!error && (
Я выше говорил вот про этот код, можем обсудить если ты считаешь что твой вариант лучше

2023-09-09 16:39 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +                        {comments.map((comment) => renderComment(comment))}
А почему бы тебе в функцию renderComment сразу не поместить map?
У тебя так или иначе комментарии это массив и даже если там будет один элемент, то проблем не будет
А результат функции сохранить в переменную и уже тут указать просто {comments} или что-то типа того

2023-09-09 16:40 UTC, Mauladen commented
В остальном всё круто, нужно только справиться с конфликтами!

2023-09-09 16:42 UTC, Mauladen requested changes

2023-09-09 16:42 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +   const { data: comments = [],error } = useGetCommentsQuery(articleId);
error лучше переименовать в isError

2023-09-12 07:55 UTC, alyonastartseva requested changes

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.module.css
> +
лишняя строка

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.module.css
> +    padding: 0 5px 0 5px;
padding: 0 5px

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.module.css
> +    color: #555;
предлагаю унифицировать цвета и вынести в переменные

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +  const articleId = "the-first-blog-article";
давай вместо этого уже useParams заиспользуем

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +   const { data: comments = [], isError } = useGetCommentsQuery(articleId);
будет здорово получить состояние загрузки запроса и добавить спиннер

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +        avatar={<Avatar src="avatar.png" />}
comment.author.avatar?

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +        title={<span className={style.title}>Author</span>}
comment.author.name?

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +            <span className={style.date}>18.01.23</span>
comment.date?

2023-09-12 07:55 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +  if(isError)
```
return isError ? (
    <Alert message="Ошибка при загрузке комментариев" type="error" />
) : (
    <div>
          <Button type="text" className={style.showComment} onClick={toggleCommentsVisibility}>
              {showComments ? 'Скрыть все комментарии' : `Показать все комментарии (${comments.length})`}
          </Button>
          {showComments && (
              <List className={style.commentList} itemLayout="horizontal">
                  {renderComments(comments)}
              </List>
          )}
    </div>
)
```

2023-09-12 07:55 UTC, alyonastartseva commented on src/redux/commentsApi.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:3001/' }),
baseUrl 'http://localhost:3001/api' вынести в shared/constants

если поменяется урл, то нужно будет поменять в одном месте, ежели чем во всех АПИ менять

2023-09-12 14:53 UTC, alyonastartseva requested changes

2023-09-12 14:53 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +  if (!id) {
useEffect(() => {
  if (!id) { 
    navigate('/')
  }
}, [ id ])

2023-09-12 14:53 UTC, alyonastartseva commented on src/components/ArticleComments/ArticleComments.tsx
> +  const { data: comments = [], isLoading, isError } = useGetCommentsQuery(articleId);
useGetCommentsQuery(String(id), { skip: !id })

2023-09-13 03:48 UTC, alyonastartseva approved these changes

2023-09-13 03:49 UTC, alyonastartseva approved these changes

2023-09-13 03:49 UTC, merged