Closes BP857394-13
alyonastartseva/blogging-platform pull request #16
Opened 2023-09-08 14:20 UTC by y-shatulo

![Снимок экрана 2023-09-08 163609](https://github.com/alyonastartseva/blogging-platform/assets/120794609/21972fde-bee6-4d4a-a854-fe3523eca1be)
![Снимок экрана 2023-09-08 163622](https://github.com/alyonastartseva/blogging-platform/assets/120794609/a27ce4f5-27ff-4300-8945-cdb3e110c33a)

На данный момент ошибка в блог айди, поскольку нет роутинга. После добавления роутинга блог айди будет получен через динамический путь в useParams
![Снимок экрана 2023-09-08 170343](https://github.com/alyonastartseva/blogging-platform/assets/120794609/4a47647b-7fd3-4fa4-a7fa-7dce7f829830)

2023-09-08 17:33 UTC, Mauladen requested changes

2023-09-08 17:33 UTC, Mauladen commented on src/pages/BlogPage/BlogPage.tsx
> +    const {data: blog} = useGetBlogQuery(blogId);
Нет обработки ошибок, хотя у статей она есть

2023-09-08 17:33 UTC, Mauladen commented on src/redux/articlesApi.ts
> +            baseUrl: `http://localhost:3001/api/blogs/`
Я думаю что baseURL `http://localhost:3001/api/` такой в данном случае

2023-09-08 17:33 UTC, Mauladen commented on src/redux/blogsApi.ts
> +            baseUrl: `http://localhost:3001/api/blogs/`
Тут тоже baseURL `http://localhost:3001/api/`

2023-09-08 17:33 UTC, Mauladen commented on src/components/ArticleCard/ArticleCard.tsx
> +            <section>{tags?.map((tag: string) => <Tag key={tag}>{tag}</Tag>)}</section>
лучше не присваивать key={tag}, можно использовать nanoid который есть в Redux Toolkit

2023-09-09 08:05 UTC, MuraPro reviewed
Проверил. Замечаний нет.

2023-09-09 17:03 UTC, y-shatulo commented on src/components/ArticleCard/ArticleCard.tsx
> +            <section>{tags?.map((tag: string) => <Tag key={tag}>{tag}</Tag>)}</section>
@Mauladen не совсем поняла про nanoid в редакс тулкит, что ты имеешь ввиду? Просто про nanoid знаю, но в их доке указано, что использование nanoid прямо в key не есть хорошо, как и в целом использование любых генераторов в ключах. Поэтому поставила в key само название тега, предполагается же, что теги будут уникальными, если я не ошибаюсь? Давай обсудим)

2023-09-09 17:03 UTC, y-shatulo commented on src/redux/blogsApi.ts
> +            baseUrl: `http://localhost:3001/api/blogs/`
Поправлю

2023-09-09 17:05 UTC, y-shatulo commented on src/pages/BlogPage/BlogPage.tsx
> +    const {data: blog} = useGetBlogQuery(blogId);
Добавлю

2023-09-09 17:14 UTC, y-shatulo commented on src/components/ArticleCard/ArticleCard.tsx
> +            <section>{tags?.map((tag: string) => <Tag key={tag}>{tag}</Tag>)}</section>
@Mauladen а все я увидела, что nanoid можно импортировать из редакс тулкит. Но все же считаю, что использовать генераторы непосредственно в ключах не нужно

2023-09-09 17:20 UTC, Mauladen commented on src/components/ArticleCard/ArticleCard.tsx
> +            <section>{tags?.map((tag: string) => <Tag key={tag}>{tag}</Tag>)}</section>
1. nanoid есть в Redux Toolkit, его не обязательно устанавливать, я тебе скидывал как он импортируется 

![image](https://github.com/alyonastartseva/blogging-platform/assets/12824589/5b159a32-4826-43b5-a158-b792a51be022)

2. Да, ты оказалась права, лучше не использовать nanoid так как между рендерами id будет меняться

2023-09-09 18:35 UTC, y-shatulo commented on src/components/ArticleCard/ArticleCard.tsx
> +            <section>{tags?.map((tag: string) => <Tag key={tag}>{tag}</Tag>)}</section>
@Mauladen да да я забыла что ты мне скидывал прям скрин, сорри, потом посмотрела повторно. Ну тогда я оставляю тег в ключе? Все остальное поправила

2023-09-12 07:23 UTC, alyonastartseva requested changes

2023-09-12 07:23 UTC, alyonastartseva commented on src/pages/BlogPage/BlogPage.tsx
> +                            <Pagination pageSize={2} defaultCurrent={1} current={currentPage} total={articles.length}
pageSize={2} - заиспользовать константу, объявленную выше

2023-09-12 07:23 UTC, alyonastartseva commented on src/pages/BlogPage/BlogPage.tsx
> +    const displayedArticles = articles.slice(startIndex, endIndex);
пагинацию лучше не реализовывать на стороне фронта, а поручить это АПИ
у json-server есть возможности для этого https://github.com/typicode/json-server#paginate

2023-09-12 07:23 UTC, alyonastartseva commented on src/pages/BlogPage/BlogPage.tsx
> +    const pageSize = 2;
константу лучше вынести из компонента

2023-09-12 07:23 UTC, alyonastartseva commented on src/pages/BlogPage/BlogPage.tsx
> +            {!isLoading && !isErrorBlog && !isErrorArticles && (
соот-но при обёртки из Spin уйдёт необходимость доп.условия - !isLoading

2023-09-12 07:23 UTC, alyonastartseva commented on src/redux/articlesApi.ts
> +            baseUrl: `http://localhost:3001/api/`
baseUrl вынести в shared/constants

если поменяется урл, то нужно будет поменять в одном месте, ежели чем во всех АПИ менять

2023-09-12 07:23 UTC, alyonastartseva commented on src/redux/blogsApi.ts
> +            baseUrl: `http://localhost:3001/api/`
заиспользовать вынесенную константу

2023-09-12 07:23 UTC, alyonastartseva commented on src/redux/store.ts
> +});
```
const mw = [ articlesApi.middleware, blogsApi.middleware ];

export const store = configureStore({
    ...,
    middleware: (getDefaultMiddleware) => getDefaultMiddleware().concat(mw)
});
```

Сократит большущую цепочку concat

2023-09-14 04:12 UTC, Mauladen requested changes

2023-09-14 04:12 UTC, Mauladen commented on src/redux/store.ts
> +const mw = [ blogsApi.middleware, articlesApi.middleware, commentsApi.middleware ];
Привет!
Вечная проблема как назвать переменную, может всё же middlewares?

2023-09-14 07:10 UTC, alyonastartseva requested changes

2023-09-14 07:10 UTC, alyonastartseva commented on src/pages/BlogPage/BlogPage.tsx
> +        const newStartIndex = (page - 1) * ARTICLES_PAGE_SIZE;
ещё подокапываюсь:
чтобы не высчитывать на фронте startIndex, endIndex - достаточно хранить номер текущей странице (start в JSON'e) и limit (количество выводов записей на странице)

поэтому можно убрать стейты для startIndex, endIndex и их вычисления в обработчике onChangePageNumber

2023-09-19 05:56 UTC, merged