Closes BP857394-10
alyonastartseva/blogging-platform pull request #18
Opened 2023-09-09 20:42 UTC by Mauladen

Реализовал отправку данных на сервер при создании статьи

2023-09-09 23:43 UTC, y-shatulo commented
Замечаний нет

2023-09-11 08:54 UTC, MuraPro reviewed
Просмотрел. Замечаний нет.

2023-09-13 06:24 UTC, alyonastartseva requested changes

2023-09-13 06:24 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +  useEffect(() => {
обработку ошибки лучше делать не в useEffect'е, а при вызове createArticle
по-моему, есть метод unwrap(), который возвращает промис, в котором в блоке catch можно таки обработать ошибку

2023-09-13 06:24 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +      void messageApi.open({
message.error('Не удалось создать статью')
так можно и без использования хука useMessage

2023-09-13 06:24 UTC, alyonastartseva commented on src/redux/api/articlesApi.ts
> +    baseUrl: 'http://localhost:3001/api/'
заиспользовать из shared/constants переменную
т.к при изменении придётся менять в одном месте, а не нескольких

2023-09-13 06:51 UTC, Mauladen commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +      void messageApi.open({
Я использую [Message](https://ant.design/components/message) из Antd

2023-09-13 06:58 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +      void messageApi.open({
message - он же и есть
error - его статический метод

но в новой версии Анта они deprecated - OK)

2023-09-13 06:58 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +      void messageApi.open({
а зачем void?

2023-09-13 12:26 UTC, alyonastartseva approved these changes

2023-09-13 12:26 UTC, merged