Closes BP857394-2 BlogList
alyonastartseva/blogging-platform pull request #19
Opened 2023-09-12 16:23 UTC by ilyacidor

Cделал список блогов
![BlogList](https://github.com/alyonastartseva/blogging-platform/assets/114821505/e85145fd-91e7-45b6-8edf-4cb260c2d148)

2023-09-12 19:38 UTC, Mauladen requested changes

2023-09-12 19:38 UTC, Mauladen commented on src/pages/BlogList/BlogList.tsx
> +  const elements = blogList.map((element: BlogType) => (
Мне кажется лучше заменить element на blog

2023-09-12 19:38 UTC, Mauladen commented on src/pages/BlogList/BlogList.tsx
> +  return <div className={styles.content}>{content}</div>;
Тернарный оператор в данном случае очень трудно читать, можно сделать через if что будет куда понятнее потому что в данном случае очень большие куски кода

2023-09-12 19:38 UTC, Mauladen commented on src/redux/slices/BlogListSlice.tsx
> +export default BlogsListSlice.reducer;
Куда лучше использовать RTK Quary, нам не зачем хранить блоги в сторе

2023-09-12 19:39 UTC, Mauladen commented
Привет!
Оставил пару комментариев, ключевое конечно это лучше использовать RTK Quary, так как там и с ошибками работать удобнее и загрузку ловить и не нужно хранить данные в сторе

2023-09-12 22:53 UTC, y-shatulo commented
Согласна с Данилом

2023-09-14 17:06 UTC, Mauladen requested changes

2023-09-14 17:06 UTC, Mauladen commented on src/types/ApiTypes.ts
> +  backgroundImage: string;
Это не строка, тип нужно использовать тот что указан

2023-09-18 20:52 UTC, ilyacidor commented on src/redux/api/blogsApi.ts
Не знаю почему, но у меня при пуше ветки blogsApi переименовывается в BlogsApi, решения в инете, которое помогло бы не нашёл, кроме как удалять файл и создавать такой же с другим названием

2023-09-18 22:39 UTC, ilyacidor commented on src/pages/BlogList/BlogList.tsx
Решил потренироваться с добавлением комментариев в коде. Если думаете, что они излишни - дайте знать

2023-09-19 18:50 UTC, alyonastartseva requested changes

2023-09-19 18:50 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +const BlogList: React.FC = () => {
import { FC } from 'react'

2023-09-19 18:50 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +  let blogListContent = <Alert type="info" message="Oops!" description="Blogs not found!" showIcon />;
давай на русский переведём

2023-09-19 18:50 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +      <Alert message="Error" description="An error has occurred! We are already working on it." type="error" showIcon />
тоже на русский

2023-09-19 18:50 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +  if (isLoading)
подход с if'ами интересный 👍🏻

2023-09-19 18:50 UTC, alyonastartseva commented on src/types/BlogList.type.ts
если этот тип нужен только для компоненты BlogList, то положить в папку BlogList --> BlogList.type.ts
если переиспользуемый - в shared/types

2023-09-19 18:50 UTC, alyonastartseva commented on src/redux/api/blogsApi.ts
> +        `/blogs?_page=${page}&_limit=8&q=${search}&_sort=createdAt&_order=${sorting}`
значение limit лучше вынести в константу

2023-09-19 18:50 UTC, alyonastartseva commented on src/redux/api/blogsApi.ts
> +    getTotalBlogs: build.query<BlogType[], string>({
а зачем этот запрос, если в запросе выше уже есть Query-параметр search?

2023-09-19 19:30 UTC, ilyacidor commented on src/pages/BlogList/BlogList.tsx
> +  if (isLoading)
Мне так посоветовали сделать)

2023-09-19 21:24 UTC, ilyacidor commented on src/redux/api/blogsApi.ts
> +    getTotalBlogs: build.query<BlogType[], string>({
Это запрос, который возвращает все найденные по query-параметру блоги, а не для отдельной страницы, как в случае с первым запросом. В случае с этим запросом сами блоги мне не нужны, нужно их количество, чтобы засунуть его в атрибут total компонента Pagination. Без query-параметра я получу все блоги с сервера, тогда при "ненулевом" search'e часть страниц будут пустыми: 
![Blogging platform - Google Chrome 20 09 2023 0_13_11](https://github.com/alyonastartseva/blogging-platform/assets/114821505/c5b1d558-88b9-4f91-a123-74ee86663c93)
![Blogging platform - Google Chrome 20 09 2023 0_14_12](https://github.com/alyonastartseva/blogging-platform/assets/114821505/85288dcc-9bda-4696-a3d6-e3a643d6a9a1)
![Blogging platform - Google Chrome 20 09 2023 0_14_29](https://github.com/alyonastartseva/blogging-platform/assets/114821505/91d78ee1-68ad-4534-a449-dd4565574c4e)

2023-09-20 12:14 UTC, alyonastartseva requested changes

2023-09-20 12:14 UTC, alyonastartseva commented on src/redux/api/blogsApi.ts
> +import { BASE_URL, blogsLimit } from '../../shared/constants';
лучше придерживаться uppercase для единообразия

2023-09-20 12:17 UTC, alyonastartseva commented on src/redux/api/blogsApi.ts
> +    getTotalBlogs: build.query<BlogType[], string>({
json-server при Query-параметрах пагинации в ответе возвращает total (X-Total-Count), можно заиспользовать его оттуда, ежели отдельным запросом доставать общее количество

2023-09-20 17:16 UTC, merged