Closes BP857394-11 Edit Acticle
alyonastartseva/blogging-platform pull request #21
Opened 2023-09-13 18:21 UTC by Mauladen

2023-09-14 12:45 UTC, EgorBrotsman commented on src/redux/api/articlesApi.ts
>  import { BASE_URL } from '../../shared/constants';
Я думаю это лучше вынести в папку api т.к к shared она не имеет отношение

2023-09-14 12:45 UTC, EgorBrotsman commented on src/components/FormEditArticle/FormEditArticle.tsx
> +export { FormEditArticle };
Тебе нужно было не новую форму создавать а адаптировать под редактирование форму создания статей

2023-09-14 12:45 UTC, EgorBrotsman commented on src/components/FormEditArticle/FormEditArticle.tsx
> +  };
Эту логику было бы не плохо вынести в кастомный hook

2023-09-15 12:38 UTC, ilyacidor commented
Проверил - всё отлично

2023-09-19 07:25 UTC, alyonastartseva requested changes

2023-09-19 07:25 UTC, alyonastartseva commented on src/components/FormEditArticle/FormEditArticle.type.ts
> +export type UseQueryResult<T> = {
RTK не экспортит тип разве?

2023-09-19 07:25 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.type.ts
> +export type TFormCreateArticleProperties = {
можно just `props`, но это дело вкуса, как говорится

2023-09-19 07:25 UTC, alyonastartseva commented on src/components/FormEditArticle/FormEditArticle.tsx
> +const FormEditArticle: FC<TFormEditArticleProperties> = ({ blogId, articleId }) => {
в целом, текущее "разнесение" на три компонента (Form, Edit, Create) - норм

но можно (и лучше) оставить одну компоненту Form, а в неё прокидывать пропсами обработчик handleFinish (его инициировать в месте, где будет использована форма)

потому что сейчас две компоненты делают одно и то же

2023-09-19 07:25 UTC, alyonastartseva commented on src/components/FormEditArticle/FormEditArticle.type.ts
> +  error?: unknown;
unknown лучше не использовать

2023-09-19 07:25 UTC, alyonastartseva commented on src/shared/components/FormArticleGeneral/FormArticle.type.ts
> +  contextHolder: unknown;
unknown лучше не использовать (пробегись по всем типам, проверь и затипизируй, плиз)

2023-09-19 17:16 UTC, alyonastartseva approved these changes

2023-09-19 17:16 UTC, merged