#Closes Bp857394_7
alyonastartseva/blogging-platform pull request #22
Opened 2023-09-14 12:31 UTC by EgorBrotsman

2023-09-15 22:08 UTC, y-shatulo reviewed
Маленькие замечания по орфографии/пунктуации, по коду замечаний нет

2023-09-15 22:08 UTC, y-shatulo commented on src/components/FormManagementBlog/FormManagementBlog.tsx
> +        description="На данный момент форму редактировать не возможно"
невозможно слитно

2023-09-15 22:08 UTC, y-shatulo commented on src/shared/components/FormBlog/FormBlog.tsx
> +      <Form.Item label="Имя блога" name="title" rules={[{ required: true, message: 'Пожалуйста укажите имя блога!' }]}>
"Пожалуйста" выдели запятой, пожалуйста)

2023-09-15 22:08 UTC, y-shatulo commented on src/shared/components/FormBlog/FormBlog.tsx
> +        rules={[{ required: true, message: 'Пожалуйста укажите имя автора!' }]}
"Пожалуйста" выдели запятой, пожалуйста)

2023-09-17 02:48 UTC, MuraPro commented on src/components/FormManagementBlog/FormManagementBlog.tsx
> +  if (type === 'editing') {
Егор я подумал а что если попробовать применить switch-case в твоем компоненте, я думаю что так было бы интуитивно понятнее и для расширения функционала удобнее что то вроде
 `
switch (isSuccess) {
    case 'editing':
      return (
        <>
          {contextHolder}
          <FormBlog handleFinish={handleFinish} contextHolder={contextHolder} initialValues={initialValues} />;
        </>
      );
    case 'create':
      return <FormBlog handleFinish={handleFinish} contextHolder={contextHolder} />;
    default:
      return (
        <Alert
          message="Что-то пошло не так"
          description="На данный момент форму редактировать невозможно"
          type="error"
        />
      );
  }
`

2023-09-17 03:09 UTC, MuraPro reviewed
В целом задумка создания хука для оптимизации функционала запросов CRUD мне нравиться я бы реализовал через switch с возможностью расширения под любые запросы к примеру чтоб можно было данный хук использовать и с коментариями. Замечаний по коду нет.

2023-09-17 03:10 UTC, MuraPro reviewed
По поводу switch советую посоветоваться с тимлидом.

2023-09-17 10:13 UTC, EgorBrotsman commented on src/components/FormManagementBlog/FormManagementBlog.tsx
> +  if (type === 'editing') {
Я решил отказаться от это идей сделал иначе

2023-09-19 17:45 UTC, alyonastartseva requested changes

2023-09-19 17:45 UTC, alyonastartseva commented on src/components/FormEditingBlog/FormEditingBlog.tsx
> +        message.error('Неудалось редактировать блог')
очепятка

2023-09-19 17:45 UTC, alyonastartseva commented on src/redux/api/constantsApi.ts
> +export const BASE_URL = 'http://localhost:3001/api/';
в shared/constants уже есть эта константа

2023-09-19 17:45 UTC, alyonastartseva commented on src/shared/components/FormBlog/FormBlog.type.ts
> +export type TFormBlog = {
в FormEditingBlog.type.ts тоже объявлен такой же тип

2023-09-19 17:45 UTC, alyonastartseva commented on src/components/FormCreateBlog/index.ts
создание блога у нас не поломалось?

2023-09-20 08:36 UTC, EgorBrotsman commented on src/redux/api/constantsApi.ts
> +export const BASE_URL = 'http://localhost:3001/api/';
по поводу данной константы я данилу писал замечание то не думаю, что её место в shared т.к она не имеет отношение к shared поэтому я перенёс её в api

2023-09-20 08:38 UTC, EgorBrotsman commented on src/components/FormCreateBlog/index.ts
нет не поломается единственное нужно будет мураду не просто выводить форму а рисовать уже мною созданную форму в shared/FormBlog и передавать в неё нужны props

2023-09-20 08:44 UTC, EgorBrotsman commented on src/shared/components/FormBlog/FormBlog.type.ts
> +export type TFormBlog = {
исправил

2023-09-20 08:44 UTC, EgorBrotsman commented on src/components/FormEditingBlog/FormEditingBlog.tsx
> +        message.error('Неудалось редактировать блог')
исправил

2023-09-20 12:27 UTC, alyonastartseva commented on src/redux/api/constantsApi.ts
> +export const BASE_URL = 'http://localhost:3001/api/';
окс, гляну и потом создам задачку на рефакторинг этого момента

2023-09-21 13:18 UTC, alyonastartseva approved these changes

2023-09-21 13:18 UTC, merged