create button for adding comment
alyonastartseva/blogging-platform pull request #23
Opened 2023-09-15 13:21 UTC by shaltus

2023-09-15 21:53 UTC, y-shatulo commented
Замечаний нет, только конфликт решить

2023-09-16 05:06 UTC, Mauladen requested changes

2023-09-16 05:06 UTC, Mauladen commented on src/components/CommentForm/CommentForm.tsx
> +    if (data.body.trim()) {
В данном случае проверка не нужна, так как это отрабатывает валидация на форме, пустой или не пустой комментарий

2023-09-16 05:06 UTC, Mauladen commented on src/components/CommentForm/CommentForm.tsx
> +          placeholder='Write your comment here...'
Тут не хватает перевода на русский :)

2023-09-17 01:42 UTC, MuraPro commented on src/components/CommentForm/CommentForm.tsx
> +  const handleSubmit = async (data: CommentFormType) => {
Я думаю что функционал создания комментария схожий с созданием статей и блогов и можно использовать ту же логику как в компоненте FormCreateArticle и FormCreatBlog для лучшего понимания логики всего проекта. На мой взгляд та функция интуитивно понятней и занимает меньше строк кода.

2023-09-17 01:46 UTC, MuraPro reviewed
В целом более замечаний нет, по поводу функционала обращения к Api, не критично, думаю этот момент стоит обсудить с тимлидом.

2023-09-19 17:59 UTC, alyonastartseva requested changes

2023-09-19 17:59 UTC, alyonastartseva commented on src/components/CommentForm/CommentForm.tsx
> +  const handleSubmit = async (data: CommentFormType) => {
на самом деле через async/await тоже норм)
тут дело предпочтений: кто-то любит async/await'ы, кто-то промисы
в проекте обычно стараются приходить к единобразию

в случае использования async/await `unwrap` не нужен
он нужен для дальнейшей цепочки промисов

2023-09-19 17:59 UTC, alyonastartseva commented on src/components/CommentForm/CommentFormType.type.ts
файл лучше назвать - `CommentForm.type.ts` - не дублировать type

2023-09-20 11:54 UTC, alyonastartseva approved these changes

2023-09-20 11:54 UTC, merged