Bp857394 6/blog_integration_with_api
alyonastartseva/blogging-platform pull request #24
Opened 2023-09-16 15:53 UTC by MuraPro

2023-09-17 10:26 UTC, shaltus commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +          content: 'Не удалось создать статью'
возможно не удалось создать блог?

2023-09-17 10:57 UTC, MuraPro commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +          content: 'Не удалось создать статью'
какая глазастая девушка ))) Поправил, спасибо

2023-09-17 18:44 UTC, Mauladen requested changes

2023-09-17 18:44 UTC, Mauladen commented on src/assets/bg.jpg
А зачем эта картинка?

2023-09-17 18:44 UTC, Mauladen commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +    form.resetFields();
Эти действия нужно делать после закрытия message, там есть атрибут onClose

2023-09-17 18:44 UTC, Mauladen commented on src/helpers/uploads.ts
> +};
Не нужная функция, она передаёт на сервер только URL, при редактировании блога нам нужно как минимум 4 свойства, я уже уменьшил их количество в другом PR

2023-09-17 18:44 UTC, Mauladen commented on src/types/ApiTypes.ts
> +  backgroundImage: string;
Это не string, должен использоваться именно тип TUploadFile

2023-09-17 18:44 UTC, Mauladen commented on src/types/ApiTypes.ts
> +  createdAt: string;
это тоже не string, на сервере используется` Date.now()`, он возвращает число

2023-09-18 14:03 UTC, MuraPro commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +    form.resetFields();
Правил

2023-09-18 14:04 UTC, MuraPro commented on src/types/ApiTypes.ts
> +  createdAt: string;
Правил

2023-09-18 14:11 UTC, MuraPro commented
Ребята посмотрите на структуру компонента FormCraeteBlog именно на функцию handleFinish, я немного переделал логику. При успешном создании происходит навигация на список блогов и там мы получаем оповещение успеха операции. Если возникает ошибка то мы остаемся на странице создания блога и получаем оповещение об ошибке. Обработка в компоненте страницы BlogListPage это для примера, чтоб вы понимали как в списке блогов будет отрабатывать данная логика, перед мержем я ее удалю. Подумаю по поводу того как именно отображать причину в случае ошибки.

2023-09-19 18:21 UTC, alyonastartseva requested changes

2023-09-19 18:21 UTC, alyonastartseva commented on src/redux/api/blogsApi.ts
> -        getBlog: build.query<TQueryBlog, string>({
удалил АПИху для получения блога по id

2023-09-22 03:31 UTC, MuraPro commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +  const handleFinish = async (data: FormCreateBlogType) => {
Поправил, забыл убрать, я ведь then использую ))

2023-09-22 03:32 UTC, MuraPro commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +        messageApi.error(
Я решил вывести ошибку, ненужно???

2023-09-22 03:33 UTC, MuraPro commented on src/components/FormCreateBlog/FormCreateBlog.tsx
> +        messageApi.error(
Поправил

2023-09-22 03:36 UTC, MuraPro commented on src/redux/api/blogsApi.ts
> -        getBlog: build.query<TQueryBlog, string>({
Поправил

2023-09-22 03:36 UTC, MuraPro commented on src/redux/api/blogsApi.ts
> +        headers: {
Поправил

2023-09-24 15:16 UTC, alyonastartseva requested changes

2023-09-24 15:16 UTC, alyonastartseva commented on src/pages/BlogPage.tsx
> +const BlogPage = () => <p>Articles List ...</p>;
подтёрлись изменения из develop (скорее всего при решении конфликтов)
пробегись, плиз, по всем изменениям и проверь, что ничего не подтёр

2023-09-25 05:34 UTC, merged