Create SearchBlog
alyonastartseva/blogging-platform pull request #29
Opened 2023-09-20 19:43 UTC by ilyacidor

Реализовал поиск блогов по названию
![Blogging platform - Google Chrome 20 09 2023 21_45_55 (2)](https://github.com/alyonastartseva/blogging-platform/assets/114821505/92b883d2-d76d-4617-b64f-5669a3903d0b)
![Blogging platform - Google Chrome 20 09 2023 21_46_25](https://github.com/alyonastartseva/blogging-platform/assets/114821505/5a704a35-902c-45ea-a3ef-1b5c3c0a8761)
![Blogging platform - Google Chrome 20 09 2023 21_51_50](https://github.com/alyonastartseva/blogging-platform/assets/114821505/0afe12d3-fbf7-4558-b92a-77094626575f)

2023-09-21 04:29 UTC, Mauladen commented
Не вижу смысл тащить lodash из-за одной функции, найди просто useDebounce хук и добавь его
Думаю так будет лучше

2023-09-22 09:08 UTC, shaltus commented
проверила, замечаний нет.

2023-09-25 09:30 UTC, alyonastartseva requested changes

2023-09-29 14:29 UTC, alyonastartseva requested changes

2023-09-29 14:29 UTC, alyonastartseva commented on src/shared/constants/useDebounce.ts
> +import { EventType } from '../../types/EventType';
shared/hooks/useDebounce.ts

2023-09-29 14:29 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +import { useDebounce } from '../../shared/constants/useDebounce';
дважды импортнул

2023-09-29 14:29 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +  const debouncedChangeSearchValue = useDebounce(changeSearchValue, 500);
500 лучше вынести в константу

2023-09-30 09:05 UTC, merged