add functional delete comment
alyonastartseva/blogging-platform pull request #30
Opened 2023-09-20 22:49 UTC by shaltus

2023-09-21 13:29 UTC, y-shatulo commented
Замечаний нет

2023-09-21 14:40 UTC, ilyacidor commented
Проверил - всё ок

2023-09-22 09:17 UTC, Mauladen commented
Мне кажется лучше использовать компонент [Popconfirm](https://ant.design/components/popconfirm)

2023-09-22 09:25 UTC, Mauladen requested changes

2023-09-22 09:25 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +type ArticleCommentsType = { id: string };
Типы лучше вынести в отдельный файл `ArticleComments.type.ts`

2023-09-22 09:25 UTC, Mauladen commented on src/components/ArticleComments/ArticleComments.tsx
> +  const [deleteComment] = useDeleteCommentMutation();
Нет обработки ошибок

2023-09-26 04:01 UTC, alyonastartseva requested changes

2023-09-28 08:34 UTC, merged