Implemented blog sorting
alyonastartseva/blogging-platform pull request #31
Opened 2023-09-21 14:08 UTC by ilyacidor

Реализовал сортировку блогов по дате публикации
![Blogging platform - Google Chrome 21 09 2023 16_58_49](https://github.com/alyonastartseva/blogging-platform/assets/114821505/a42d9c62-c651-4dc9-a9d3-34b76cfe77c5)
![Blogging platform - Google Chrome 21 09 2023 16_59_06 (2)](https://github.com/alyonastartseva/blogging-platform/assets/114821505/04a986b2-cbfa-43e8-b756-f046980ba72d)

2023-09-21 15:04 UTC, y-shatulo commented on src/pages/BlogList/BlogList.tsx
> +        <p className={styles.sorting__title}>Сортировка по дате публикации</p>
Чисто субъективно, мне кажется можно убрать "Сортировка" и оставить просто "Дата публикации"

2023-09-21 15:04 UTC, y-shatulo commented on src/pages/BlogList/BlogList.tsx
> +          }}
Можно вынести в отдельную функцию и передать ее в onChange

2023-10-03 07:11 UTC, MuraPro reviewed
Проверил, замечаний нет.

2023-10-03 12:57 UTC, alyonastartseva requested changes

2023-10-03 12:57 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> +  const changeSortingValue = (value: OptionsValues) => setSortingValue(value)
при изменении сортировки запрос отправляется?

2023-10-03 13:27 UTC, ilyacidor commented on src/pages/BlogList/BlogList.tsx
> +  const changeSortingValue = (value: OptionsValues) => setSortingValue(value)
Исправил

2023-10-03 16:27 UTC, alyonastartseva approved these changes

2023-10-03 16:27 UTC, merged