#Closes Bp857394-25_create_page_authorization
alyonastartseva/blogging-platform pull request #33
Opened 2023-09-22 09:51 UTC by EgorBrotsman

2023-09-22 11:07 UTC, y-shatulo commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      <Form.Item label="Password" name="password" rules={[{ required: true, message: 'Пожалйста введите пароль!' }]}>
Опечатка, и добавь, плиз запятые после "Пожалуйста")

2023-09-22 11:07 UTC, y-shatulo commented on src/shared/components/SubmitButton/SubmitButton.tsx
> +      Войти
Исправила у себя в PR, посмотри, чтобы компонент можно было переиспользовать, в него надо еще передавать текст кнопки

2023-09-25 04:04 UTC, Mauladen requested changes

2023-09-25 04:04 UTC, Mauladen commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  };
Уведомления лучше выводить не в консоль

2023-09-25 04:04 UTC, Mauladen commented on src/shared/components/SubmitButton/SubmitButton.tsx
> +};
Вынеси типы в отдельный файл

2023-09-25 04:04 UTC, Mauladen commented on yarn.lock
yarn.lock добавился, а он не нужен

2023-09-25 07:42 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  };
С меня требовалась лишь вёрстка это пока заглушка я ж не знаю какая будет дальше логика

2023-09-28 08:49 UTC, alyonastartseva requested changes

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.module.scss
> +.form{
наверняка можно вынести общие стили для страницы авторизации и регистрации

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +
лишние пробелы

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +
тоже самое :)

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const [error, setError] = useState(false)
булевые переменные/стейты принято начинать с 'is' - isError, isMultiple и т.д

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const onFinish = (values: any) => {
затипизировать any

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const onFinishFailed = (errorInfo: any) => {
затипизировать any

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {error ? <span className="error-info">Неверный логин или пороль</span> : null}
посмотри, как можно сделать средствами ant'а этот мессадж

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {error ? <span className="error-info">Неверный логин или пороль</span> : null}
пАроль

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
status={error ? 'error' : undefined} - этого можно избежать, в Анте есть динамическая установка ошибок для полей форм

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
ПожалУйста

2023-09-28 08:49 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        Нет аккаунта? <Link to="#">Зарегестрироваться</Link>
ЗарегИстрироваться

2023-09-28 09:03 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.module.scss
> +.form{
Исправил

2023-09-28 09:04 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +
исправил

2023-09-28 09:09 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const onFinish = (values: any) => {
исправил

2023-09-28 09:10 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const onFinishFailed = (errorInfo: any) => {
исправил

2023-09-28 09:11 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        Нет аккаунта? <Link to="#">Зарегестрироваться</Link>
исправил

2023-09-28 09:37 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
Речь про это идёт?
![2023-09-28_12-36-34](https://github.com/alyonastartseva/blogging-platform/assets/58328829/938ac6e3-6d0f-40c5-96e6-b2f8f4e21833)

2023-09-28 09:43 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {error ? <span className="error-info">Неверный логин или пороль</span> : null}
А тут только если Alert использовать, другого я в формах не нашёл, и я не уверен что alt тут уместен

2023-09-28 09:43 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {error ? <span className="error-info">Неверный логин или пороль</span> : null}
Исправил

2023-09-28 09:45 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +  const [error, setError] = useState(false)
исправил

2023-09-28 10:20 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
я же здесь не валидацию делаю, а в случае если авторизыция пошла с ошибкой

2023-09-28 13:32 UTC, alyonastartseva requested changes

2023-09-28 13:32 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
речь про setFields: в onFinishFailed можно установить месадж и подсветить поля с помощью метода setFields

2023-09-28 16:13 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password status={error ? 'error' : undefined} />
исправил

2023-09-28 16:53 UTC, alyonastartseva requested changes

2023-09-28 16:53 UTC, alyonastartseva commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {isError ? <Alert message="Неверный логин или пароль" type='error' /> : null}
message можно в errors положить (оба поля будут подсвечены красным, а у пароля (снизу) будет сообщение)

2023-09-29 08:21 UTC, EgorBrotsman commented on src/components/FormAuthorization/FormAuthorization.tsx
> +      {isError ? <Alert message="Неверный логин или пароль" type='error' /> : null}
исправил

2023-09-29 14:14 UTC, alyonastartseva requested changes

2023-09-29 14:14 UTC, alyonastartseva commented on src/assets/styles/IdentificationForm.module.scss
> +.error-info{
в этом классе уже нет необходимости

2023-09-30 09:14 UTC, merged