add privateRoute
alyonastartseva/blogging-platform pull request #38
Opened 2023-09-27 14:01 UTC by shaltus

2023-09-27 17:29 UTC, MuraPro reviewed
Проверил. Замечаний нет.

2023-09-28 09:12 UTC, alyonastartseva requested changes

2023-09-28 09:12 UTC, alyonastartseva commented on src/routes/index.tsx
> +          {' '}
а зачем {' '}? (и ниже)

2023-09-28 11:08 UTC, shaltus commented on src/routes/index.tsx
> +          {' '}
странно )  как там оказался? 
уберу

2023-09-29 13:48 UTC, merged