Closes-BP857394-33-RouteToBlogPage
alyonastartseva/blogging-platform pull request #43
Opened 2023-09-30 14:32 UTC by ilyacidor

Сделал навигацию со списка блогов на страницу выбранного блога

![Blogging platform - Google Chrome 30 09 2023 17_03_23](https://github.com/alyonastartseva/blogging-platform/assets/114821505/e135aca7-04fa-4e09-8f24-35a162ecf76d)
![Blogging platform - Google Chrome 30 09 2023 16_49_36](https://github.com/alyonastartseva/blogging-platform/assets/114821505/53e2b0ec-b6c3-40af-8863-dffec8c63c23)

2023-10-01 14:17 UTC, MuraPro commented on src/pages/BlogList/BlogList.tsx
> +          avatarImage={blog.author}
этого свойства нет в db

2023-10-03 06:58 UTC, MuraPro reviewed
Проверил, замечаний нет.

2023-10-03 16:33 UTC, alyonastartseva requested changes

2023-10-03 16:33 UTC, alyonastartseva commented on src/components/CardBlog/CardBlog.tsx
> +    <Meta avatar={<Avatar src="" />} title={title} />
лучше убрать пропс avatar, если он не используется

2023-10-03 19:10 UTC, merged