Api integration with components
alyonastartseva/blogging-platform pull request #45
Opened 2023-10-01 11:12 UTC by MuraPro

2023-10-01 15:18 UTC, MuraPro commented
![Безымянный](https://github.com/alyonastartseva/blogging-platform/assets/78410784/f06694df-49db-41aa-a9a8-b8a4ec23ff83)

2023-10-01 15:46 UTC, ilyacidor commented on src/components/FormCreateArticle/FormCreateArticle.tsx
> +import { Alert, message } from 'antd';
Alert не используется

2023-10-01 15:46 UTC, ilyacidor commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password name="password" />
Опечатка в "пожалуйста", и мне кажется зря ты перевел пароль и почту на английский в label'ах, типо у нас всё приложение на русском будет.

2023-10-01 17:51 UTC, shaltus commented
Проверила ,замечаний нет

2023-10-03 05:35 UTC, MuraPro commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password name="password" />
это не мой компонент, я его не писал, опечатку поправлю

2023-10-03 05:40 UTC, MuraPro commented on src/components/FormAuthorization/FormAuthorization.tsx
> +        <Input.Password name="password" />
И вообще это были старые изменения, там конфликт был ветьвей, я поправил, там все нормально теперь.

2023-10-03 19:08 UTC, alyonastartseva requested changes

2023-10-03 19:08 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.type.ts
> +  changeVisibility?: any;
any!

если это функция, меняющая видимость модалки, то лучше "обозвать" changeVisibilityModal - так читается побыстрее

2023-10-03 19:08 UTC, alyonastartseva commented on src/components/FormCreateArticle/FormCreateArticle.type.ts
> +  changeVisibility?: any;
а вообще лучше handleFinish вынести из этого компонента и передавать его пропсом
так компонент (форма) будет отвечать только за отрисовку

2023-10-03 19:08 UTC, alyonastartseva commented on src/components/FormEditingBlog/FormEditingBlog.tsx
> +      .then(() => changeVisibility())
аналогично как и с созданием

2023-10-03 19:08 UTC, alyonastartseva commented on src/components/FormEditingBlog/FormEditingBlog.type.ts
> +  userId?: string;
тип одинаковый с TFormCreateArticleProperties

2023-10-03 19:08 UTC, alyonastartseva commented on src/helpers/token.ts
> +  const token: any = localStorage.getItem('token');
any

2023-10-03 19:08 UTC, alyonastartseva commented on src/pages/BlogList/BlogList.tsx
> -import { Pagination, Spin, Alert, Input } from 'antd';
тоже перетёрт поиск

2023-10-03 19:08 UTC, alyonastartseva commented on src/shared/components/FormBlog/FormBlog.tsx
> -const FormBlog: FC<TFormBlogProperties> = ({ handleFinish, initialValues }) => {
почему initialValues удалил?

2023-10-03 19:08 UTC, alyonastartseva commented on src/shared/components/ModalGeneral/ModalGeneral.tsx
> +        {Children.map<React.ReactNode, React.ReactNode>(children, (child) => {
зачем?

2023-10-04 16:50 UTC, MuraPro commented on src/components/FormCreateArticle/FormCreateArticle.type.ts
> +  changeVisibility?: any;
Поправил

2023-10-04 16:50 UTC, MuraPro commented on src/components/FormEditingBlog/FormEditingBlog.tsx
> +      .then(() => changeVisibility())
ok

2023-10-04 16:51 UTC, MuraPro commented on src/helpers/token.ts
> +  const token: any = localStorage.getItem('token');
Поправил

2023-10-04 16:51 UTC, MuraPro commented on src/pages/BlogList/BlogList.tsx
> -import { Pagination, Spin, Alert, Input } from 'antd';
Не совсем понял что я сделал

2023-10-04 16:52 UTC, MuraPro commented on src/shared/components/FormBlog/FormBlog.tsx
> -const FormBlog: FC<TFormBlogProperties> = ({ handleFinish, initialValues }) => {
Поправил

2023-10-04 16:54 UTC, MuraPro commented on src/shared/components/ModalGeneral/ModalGeneral.tsx
> +        {Children.map<React.ReactNode, React.ReactNode>(children, (child) => {
Потому что я не нашел как еще передать функцию закрытия модалки

2023-10-06 09:38 UTC, merged