Bp857394 1 create card blog
alyonastartseva/blogging-platform pull request #6
Opened 2023-09-01 15:12 UTC by EgorBrotsman

2023-09-02 04:15 UTC, Mauladen commented on package.json
> +    "ts-plugin-scss-modules": "^0.1.2",
Я открыл документацию, посмотрел что это нигде не используется, попробовал удалить и ничего не изменилось, думаю для решению проблемы с импортом модулей хватает @types/css-modules

2023-09-02 04:15 UTC, Mauladen commented on src/components/CardBlog/CardBlog.module.scss
> +}
Используй пожалуйста Prettier

2023-09-02 04:15 UTC, Mauladen commented on package.json
> +    "@types/css-modules": "^1.0.2",
Стоит перенести в devDependencies

2023-09-02 19:15 UTC, shaltus commented
Замечание отсутствует! 
 проверено!

2023-09-04 08:50 UTC, y-shatulo commented
Замечания отсутствуют

2023-09-05 07:21 UTC, alyonastartseva requested changes

2023-09-05 07:26 UTC, EgorBrotsman commented on src/components/App/index.ts
> +// eslint-disable-next-line import/prefer-default-export
Потому-что он ругается хотя вроде всё верно путь верный 
![image](https://github.com/alyonastartseva/blogging-platform/assets/58328829/6a4a433f-8c44-4c10-aa5b-e73f911faad3)

2023-09-05 07:32 UTC, EgorBrotsman commented on src/components/CardBlog/CardBlog.tsx
> +// eslint-disable-next-line import/no-extraneous-dependencies
Исправил

2023-09-05 07:58 UTC, EgorBrotsman commented on yarn.lock
Удалил

2023-09-05 07:58 UTC, EgorBrotsman commented on src/types/CardBlogType.ts
> +export type DateConversionType = (date: string) => string;
Исправил

2023-09-05 07:59 UTC, EgorBrotsman commented on src/index.tsx
> +// eslint-disable-next-line import/no-unresolved
Исправил

2023-09-05 07:59 UTC, EgorBrotsman commented on src/components/CardBlog/index.ts
> +// eslint-disable-next-line import/prefer-default-export
исправил

2023-09-05 07:59 UTC, EgorBrotsman commented on src/components/CardBlog/CardBlog.tsx
> +  return (
исправил

2023-09-05 07:59 UTC, EgorBrotsman commented on src/components/CardBlog/CardBlog.tsx
> +const CardBlog = (properties: CardBlogPropertiesType) => {
исправил

2023-09-05 08:00 UTC, EgorBrotsman commented on src/components/CardBlog/CardBlog.tsx
> +const dateConversion: DateConversionType = (date) => dayjs(date).format('DD.MM.YYYY');
Типизировано data может быть только string и ничем больше

2023-09-05 08:00 UTC, EgorBrotsman commented on src/components/App/index.ts
> +// eslint-disable-next-line import/prefer-default-export
исправлено

2023-09-05 08:54 UTC, merged