Closes BP857394-12
alyonastartseva/blogging-platform pull request #9
Opened 2023-09-04 08:29 UTC by y-shatulo

![Снимок экрана 2023-09-02 202842](https://github.com/alyonastartseva/blogging-platform/assets/120794609/3ce45d99-5b71-4de6-a5c4-a812d985f225)

2023-09-04 10:50 UTC, shaltus reviewed
вполне код читаем

2023-09-04 10:50 UTC, shaltus commented on src/components/ArticleCard/ArticleCard.tsx
> +const ArticleCard: React.FC<ArticleCardType> = (properties) => {
Вместо того чтобы передавать properties и затем извлекать свойства из него, вы можете сразу деструктурировать пропсы.

2023-09-04 11:27 UTC, y-shatulo commented on src/components/ArticleCard/ArticleCard.tsx
> +const ArticleCard: React.FC<ArticleCardType> = (properties) => {
Сделано

2023-09-04 16:48 UTC, Mauladen commented
Нужно удалить файлы .idea, там несколько файлов подтянулось

2023-09-04 16:54 UTC, Mauladen commented
Так же не увидел аватар пользователя который создал статью, для этого можно использовать [готовый компонент](https://ant.design/components/avatar)

2023-09-04 17:26 UTC, y-shatulo commented
> Так же не увидел аватар пользователя который создал статью, для этого можно использовать [готовый компонент](https://ant.design/components/avatar)

Судя по скетчам, статьи будут находиться не в общем списке, а в блоге конкретного автора. Плюс это не полноразмерная статья, а карточка статьи в списке. Поэтому считаю, что аватар в данном контексте в карточке статьи не нужен

2023-09-04 17:27 UTC, y-shatulo commented
> Нужно удалить файлы .idea, там несколько файлов подтянулось

принято, удаляю

2023-09-05 14:19 UTC, alyonastartseva requested changes

2023-09-05 14:19 UTC, alyonastartseva commented on src/components/ArticleCard/index.ts
Пустой файлик так и задумывался?

2023-09-05 14:19 UTC, alyonastartseva commented on src/components/ArticleCard/ArticleCard.tsx
> +const ArticleCard: React.FC<ArticleCardType> = ({ title, body, author, tags }) => {
можно FC  импортнуть из React'а:

`import React, { FC } from 'react'`

2023-09-05 14:29 UTC, y-shatulo commented on src/components/ArticleCard/index.ts
нет) исправила

2023-09-05 15:00 UTC, alyonastartseva approved these changes

2023-09-05 15:00 UTC, merged